# Generated by Django 4.0.4 on 2022-05-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articale',
            old_name='auuthor',
            new_name='author',
        ),
    ]
